const foods = [
  {
    id: 1,
    name: "Seblak Spesial",
    name_en: "Special Seblak",
    category: "bakso",
    price: "Rp 10.000",
    likes: 342,
    rating: 4.9,
    image: "assets/foto-seblak.png",
    color: "#E53E3E",
    description: "Seblak dengan bumbu kencur yang kuat, isian kerupuk basah, makaroni, sosis, dan bakso. Level pedas bisa disesuaikan.",
    description_en: "Authentic Seblak with strong aromatic ginger seasoning, filled with wet crackers, macaroni, sausage, and meatballs. Spicy levels are adjustable.",
    ingredients: ["Kerupuk Basah", "Makaroni", "Sosis", "Bakso", "Bumbu Kencur Spesial"],
    ingredients_en: ["Wet Crackers", "Macaroni", "Sausage", "Meatballs", "Special Ginger Seasoning"],
    flavors: ["Level 1", "Level 2", "Level 3", "Level 4", "Level 5"],
    flavors_en: ["Level 1", "Level 2", "Level 3", "Level 4", "Level 5"],
  },
  {
    id: 2,
    name: "Aneka Sosis dan Tempura",
    name_en: "Assorted Sausage & Tempura",
    category: "bakso",
    price: "Rp 5.000",
    likes: 156,
    rating: 4.7,
    image: "assets/aneka-sosis.png",
    color: "#FF6B35",
    description: "Berbagai macam gorengan sosis dan tempura dengan olesan saus dan cabe.",
    description_en: "A variety of fried sausages and tempura served with savory sauce and chili topping.",
    ingredients: ["Sosis Sapi", "Sosis Ayam", "Bakso Ikan", "Tempura", "Nugget", "Bakpao", "Siomay"],
    ingredients_en: ["Beef Sausage", "Chicken Sausage", "Fish Balls", "Tempura", "Nugget", "Bakpao", "Siomay"],
    flavors: ["Saus Pedas", "Saus Tidak Pedas", "Bumbu Balado", "Bumbu Jagung"],
    flavors_en: ["Spicy Sauce", "Non-Spicy Sauce", "Balado Seasoning", "Corn Seasoning"],
  },
  {
    id: 3,
    name: "Sosis Kocek",
    name_en: "Sosis Kocek (Stirred Sausage)",
    category: "bakso",
    price: "Rp 5.000",
    likes: 210,
    rating: 4.8,
    image: "assets/sosis-kocek.png",
    color: "#F6C90E",
    description: "Sosis goreng yang dipotong-potong dan diaduk dengan paduan cabe ulek pedas gurih dan bumbu spesial.",
    description_en: "Fried sausages cut into pieces and stirred with a blend of savory crushed chili and special seasonings.",
    ingredients: ["Sosis Pilihan", "Saus Pedas", "Cabe Ulek", "Bumbu Balado", "Bumbu Jagung"],
    ingredients_en: ["Premium Sausage", "Spicy Sauce", "Crushed Chili", "Balado Seasoning", "Corn Seasoning"],
    flavors: ["Level 1", "Level 2", "Level 3", "Level 4", "Level 5"],
    flavors_en: ["Level 1", "Level 2", "Level 3", "Level 4", "Level 5"],
  },
  {
    id: 4,
    name: "Tahu Kocek",
    name_en: "Tahu Kocek (Stirred Tofu)",
    category: "bakso",
    price: "Rp 5.000",
    likes: 189,
    rating: 4.6,
    image: "assets/tahu-kocek.png",
    color: "#4CAF50",
    description: "berupa tahu pong diisi adonan aci (tapioka & terigu), digoreng, lalu diulek/dicampur dengan sambal bawang pedas.",
    description_en: "Fried 'tahu pong' filled with tapioca dough, then crushed and mixed with spicy garlic chili sauce.",
    ingredients: ["Tahu Putih", "Tepung", "Cabe Ulek", "Saus Pedas", "Bumbu Balado", "Bumbu Jagung"],
    ingredients_en: ["White Tofu", "Flour", "Crushed Chili", "Spicy Sauce", "Balado Seasoning", "Corn Seasoning"],
    flavors: ["Level 1", "Level 2", "Level 3", "Level 4", "Level 5"],
    flavors_en: ["Level 1", "Level 2", "Level 3", "Level 4", "Level 5"],
  },
  {
    id: 5,
    name: "Es Campur Segar",
    name_en: "Fresh Es Campur",
    category: "minuman",
    price: "Rp 5.000",
    likes: 275,
    rating: 4.9,
    image: "assets/es-campur.png",
    color: "#3B82F6",
    description: "Minuman es campur dengan isian buah-buahan, cincau, kolang-kaling, dan sirup manis yang menyegarkan.",
    description_en: "A refreshing mixed ice drink filled with various fruits, grass jelly, sugar palm fruit, and sweet syrup.",
    ingredients: ["Buah Segar", "Cincau", "Kolang-kaling", "Sirup", "Susu Kental Manis"],
    ingredients_en: ["Fresh Fruits", "Grass Jelly", "Sugar Palm Fruit", "Syrup", "Condensed Milk"],
    flavors: ["Kurangi Manis", "Manis", "Lebih Manis"],
    flavors_en: ["Less Sweet", "Normal Sweet", "Extra Sweet"],
  },
  {
    id: 6,
    name: "Es Teajus",
    name_en: "Es Teajus",
    category: "minuman",
    price: "Rp 1.000",
    likes: 120,
    rating: 4.5,
    image: "assets/es-teajus.png",
    color: "#FF6B35",
    description: "Minuman teh praktis yang segar, cocok untuk menemani hidangan pedas seblak dan kocek.",
    description_en: "Instant refreshing tea drink, perfect to accompany spicy dishes like Seblak or Kocek.",
    ingredients: ["Teajus", "Es Batu", "Air Mineral"],
    ingredients_en: ["Teajus Powder", "Ice Cubes", "Mineral Water"],
    flavors: ["Gula Batu", "Melati", "Lemon"],
    flavors_en: ["Rock Sugar", "Jasmine", "Lemon"],
  },
  {
    id: 7,
    name: "Es Pop Ice",
    name_en: "Es Pop Ice",
    category: "minuman",
    price: "Rp 3.000",
    likes: 150,
    rating: 4.9,
    image: "assets/varian-popice.png",
    color: "#00ff22ff",
    description: "Minuman pop ice dengan berbagai macam varian rasa, cocok untuk menemani hidangan pedas seblak dan kocek.",
    description_en: "Pop Ice milk drink with various flavors, great for cooling down after a spicy meal.",
    ingredients: ["Pop Ice", "Es Batu", "Air Mineral"],
    ingredients_en: ["Pop Ice Powder", "Ice Cubes", "Mineral Water"],
    flavors: ["Stroberi", "Coklat", "Vanilla", "Taro", "Melon", "Durian", "Mangga", "Permen Karet"],
    flavors_en: ["Strawberry", "Chocolate", "Vanilla", "Taro", "Melon", "Durian", "Mango", "Bubble Gum"],
  },
  {
    id: 8,
    name: "Es JasJus",
    name_en: "Es JasJus",
    category: "minuman",
    price: "Rp 1.000",
    likes: 150,
    rating: 4.9,
    image: "assets/varian-jasjus.png",
    color: "#f3f25aff",
    description: "Minuman pop ice dengan berbagai macam varian rasa, cocok untuk menemani hidangan pedas seblak dan kocek.",
    description_en: "Instant fruit-flavored drink with various refreshing options.",
    ingredients: ["Bubuk JasJus", "Es Batu", "Air Mineral"],
    ingredients_en: ["JasJus Powder", "Ice Cubes", "Mineral Water"],
    flavors: ["Stroberi", "Sirsak", "Mangga", "Jeruk", "anggur", "Jeruk Peras", "Jeruk Nipis", "Melon"],
    flavors_en: ["Strawberry", "Soursop", "Mango", "Orange", "Grape", "Squeezed Orange", "Lime", "Melon"],
  },

];

const testimonials = [
  {
    id: 1,
    name: "eko",
    role: "Pelanggan",
    comment: "warung mnatp bagus murah juga dan strategis",
    rating: 5,
    avatar: "assets/man.png"
  },
  {
    id: 2,
    name: "Fais",
    role: "Pelanggan",
    comment: "saya sangat suka dengan seblak nya, harganya terjangkau dan rasanya mantap",
    rating: 5,
    avatar: "assets/man.png"
  },
  {
    id: 3,
    name: "SUGIK",
    role: "Pelanggan",
    comment: "makanannya enak enak",
    rating: 5,
    avatar: "assets/man.png"
  },
  {
    id: 4,
    name: "rafi",
    role: "Pelanggan",
    comment: "asli eenak banget makanannya raurr",
    rating: 5,
    avatar: "assets/man.png"
  },
  {
    id: 5,
    name: "Kiki",
    role: "Pelanggan",
    comment: "Emm soal rasa dijamin mantulll",
    rating: 5,
    avatar: "assets/woman.png"
  },
  {
    id: 6,
    name: "Arief",
    role: "Pelanggan",
    comment: "Soal rasa gak usah diragukan lagi harga bersahabat",
    rating: 5,
    avatar: "assets/man.png"
  }
];
