const foods = [
  {
    id: 1,
    name: "Seblak Spesial",
    category: "bakso",
    price: "Rp 15.000",
    likes: 342,
    rating: 4.9,
    image: "assets/foto-seblak.png",
    color: "#E53E3E",
    description: "Seblak dengan bumbu kencur yang kuat, isian kerupuk basah, makaroni, sosis, dan bakso. Level pedas bisa disesuaikan.",
    ingredients: ["Kerupuk Basah", "Makaroni", "Sosis", "Bakso", "Bumbu Kencur Spesial"],
  },
  {
    id: 2,
    name: "Aneka Sosis Bakar",
    category: "bakso",
    price: "Rp 10.000",
    likes: 156,
    rating: 4.7,
    image: "assets/aneka-sosis.png",
    color: "#FF6B35",
    description: "Berbagai macam sosis dan bakso bakar dengan olesan saus BBQ dan mayones yang melimpah.",
    ingredients: ["Sosis Sapi", "Sosis Ayam", "Bakso Ikan", "Saus BBQ", "Mayones"],
  },
  {
    id: 3,
    name: "Sosis Kocek",
    category: "bakso",
    price: "Rp 12.000",
    likes: 210,
    rating: 4.8,
    image: "assets/sosis-kocek.png",
    color: "#F6C90E",
    description: "Sosis goreng yang dipotong-potong dan diaduk dengan bumbu bubuk pedas gurih serta irisan daun jeruk.",
    ingredients: ["Sosis Pilihan", "Bumbu Pedas Gurih", "Daun Jeruk", "Minyak Wijen"],
  },
  {
    id: 4,
    name: "Tahu Kocek",
    category: "bakso",
    price: "Rp 10.000",
    likes: 189,
    rating: 4.6,
    image: "assets/tahu-kocek.png",
    color: "#4CAF50",
    description: "Tahu goreng krispi yang dikocek dengan bumbu rahasia R3 yang pedas dan menggugah selera.",
    ingredients: ["Tahu Putih", "Tepung Krispi", "Bumbu Kocek R3", "Cabai Rawit"],
  },
  {
    id: 5,
    name: "Es Campur Segar",
    category: "minuman",
    price: "Rp 12.000",
    likes: 275,
    rating: 4.9,
    image: "assets/es-campur.png",
    color: "#3B82F6",
    description: "Minuman es campur dengan isian buah-buahan, cincau, kolang-kaling, dan sirup manis yang menyegarkan.",
    ingredients: ["Buah Segar", "Cincau", "Kolang-kaling", "Sirup", "Susu Kental Manis"],
  },
  {
    id: 6,
    name: "Es Teajus",
    category: "minuman",
    price: "Rp 5.000",
    likes: 120,
    rating: 4.5,
    image: "assets/es-teajus.png",
    color: "#FF6B35",
    description: "Minuman teh praktis yang segar, cocok untuk menemani hidangan pedas seblak dan kocek.",
    ingredients: ["Teajus", "Es Batu", "Air Mineral"],
  },
];

// const testimonials = [
//   {
//     id: 1,
//     name: "Budi Santoso",
//     role: "Pelanggan Setia",
//     comment: "Seblaknya bener-bener mantap! Bumbunya meresap dan pedasnya pas banget di lidah.",
//     rating: 5,
//     avatar: "https://i.pravatar.cc/150?u=budi"
//   },
//   {
//     id: 2,
//     name: "Siti Aminah",
//     role: "Pecinta Pedas",
//     comment: "Sosis koceknya juara, bumbunya beda dari yang lain. Tahu koceknya juga krispi banget.",
//     rating: 5,
//     avatar: "https://i.pravatar.cc/150?u=siti"
//   },
//   {
//     id: 3,
//     name: "Andi Wijaya",
//     role: "Pelajar",
//     comment: "Harganya ramah di kantong pelajar, porsinya banyak. Es campurnya seger banget abis makan yang pedes-pedes.",
//     rating: 4,
//     avatar: "https://i.pravatar.cc/150?u=andi"
//   },
//   {
//     id: 4,
//     name: "Rina Kartika",
//     role: "Ibu Rumah Tangga",
//     comment: "Camilan favorit keluarga! Tahu koceknya nagih banget, anak-anak juga suka sosis bakarnya karena sausnya enak.",
//     rating: 5,
//     avatar: "https://i.pravatar.cc/150?u=rina"
//   },
//   {
//     id: 5,
//     name: "Dedi Kurniawan",
//     role: "Ojek Online",
//     comment: "Sering dapet orderan di sini, emang baunya wangi banget bikin pengen beli terus. Akhirnya nyoba sendiri emang mantap!",
//     rating: 5,
//     avatar: "https://i.pravatar.cc/150?u=dedi"
//   },
//   {
//     id: 6,
//     name: "Maya Sari",
//     role: "Food Blogger",
//     comment: "Seblak dengan kearifan lokal yang dieksekusi dengan sangat baik. Kebersihan tempat dan pelayanannya jempolan.",
//     rating: 5,
//     avatar: "https://i.pravatar.cc/150?u=maya"
//   }
// ];
